<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishAot>true</PublishAot>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
	<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mile.Xaml" Version="2.5.1250" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
  </ItemGroup>

</Project>